### ISSUE TITLE
Create separate table for listing shift names

### ISSUE THREAD

**Issue by itsrachelfish** [playatech/laravel-voldb#31]
Instead of letting admins name shifts arbitrarily, the shifts table should be used to define shift names per department. This would also be a good opportunity to add descriptions for shifts (issue #21).

The current ```shifts``` table should be split into ```shifts``` and ```shift_data``` tables. The ```shift_data``` table would define the information about shifts available within departments and ```shifts``` table would define the dates, times, duration, and the number of volunteers required.

When editing a department there should be a list of available shifts as well as a button to create new ones. When creating event shifts, a dropdown should appear that lists available shift names instead of a text field.

**Todo**
- [x] Create migration for new shift_data table
- [x] Create migration to add number of volunteers to shifts table
- [x] Update relationships to use new shift_data table
- [x] Update templates for displaying data from shift_data
- [x] Create new templates for creating / editing shift_data
- [x] Update schedule creation to use new shift_data table

**Comment by IzKen** [comment]
I'm not clear where a shift name comes in. Previous we had roles, then then shifts were setup under the role. But the shifts weren't named. So by "shift name" do you mean basically the same thing as a Role in VolDB 2016 and earlier?

Will leads for a dept still be able to create their own shift names on the fly as needed? Most departments have 2-5 shifts and their names are normally unique to that dept, so I don't see how having a drop-down, which has to be populated 1st is helping much. 

As a general rule, I would say anything that wasn't in the previous VolDB doesn't need to be a high priority or scheduled for the Ground Control Retreat. In the past VolDB there was no drop-down for role names and I think this is a nice to have feature.

**Comment by itsrachelfish** [comment]
Yes, "shifts" in this database are essentially the same thing as "roles" in the old database. Currently when creating a shift a text input is used that lets admins type anything they want as a shift name. Dana thinks is too flexible and could lead to issues in reporting if there are typos.

**Comment by kelsh** [comment]
Have admin's create department specific shift name prefixes, and then whoever can add whatever shift names as needed once selecting a department prefix?  Flexible but constrained somewhat?

**Comment by itsrachelfish** [comment]
These updates have been (mostly) finished as of commit 1c43f10ef43aabae367a3c79c3dbc15d1e0a33b3
